name: Install Sublime Text (Self-Hosted)

on:
  workflow_dispatch:  # Trigger manually

jobs:
  install-sublime:
    runs-on: self-hosted  # use your own runner

    steps:
      - name: Check if Sublime is already installed
        run: |
          if command -v subl > /dev/null; then
            echo "Sublime Text is already installed."
            subl --version
            exit 0
          fi

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y wget gnupg apt-transport-https ca-certificates

      - name: Add Sublime Text repo and install
        run: |
          wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo gpg --dearmor -o /usr/share/keyrings/sublimehq-archive-keyring.gpg

          echo "deb [signed-by=/usr/share/keyrings/sublimehq-archive-keyring.gpg] https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

          sudo apt update
          sudo apt install -y sublime-text

      - name: Confirm installation
        run: subl --version
