name: Test Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  run-on-self-hosted:
    runs-on: self-hosted  # or use: [self-hosted, linux] or any custom label
    steps:
      - name: Print Hello
        run: echo "Hello from self-hosted runner!"
