name: Test Self-Hosted Runner

on:
  push:
    branches: [main]

jobs:
  run-on-self-hosted:
    runs-on: self-hosted  # or use: [self-hosted, linux] if needed
    steps: 
      - name: Print Hello
        run: echo "Hello from self-hosted runner!"
